
import React from 'react';
import { CountryCode } from '../lib/types';

interface LegalFooterProps {
  country?: CountryCode;
}

export const LegalFooter: React.FC<LegalFooterProps> = ({ country = 'US' }) => {
  const currentYear = new Date().getFullYear();

  return (
    <footer className="bg-slate-50 border-t border-slate-200 py-10 mt-auto">
      <div className="max-w-6xl mx-auto px-6">
         <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
            <div>
              <h5 className="text-xs font-bold text-slate-700 uppercase tracking-wider mb-3">Legal Disclaimer</h5>
              <p className="text-[10px] text-slate-400 leading-relaxed">
                This application is designed for <strong>educational and informational purposes only</strong>. It does not constitute financial, investment, tax, or legal advice. 
                The projections generated by this tool are hypothetical simulations based on user-defined assumptions and historical data, which are not guarantees of future performance.
              </p>
            </div>
            <div>
              <h5 className="text-xs font-bold text-slate-700 uppercase tracking-wider mb-3">Regional Compliance</h5>
              <p className="text-[10px] text-slate-400 leading-relaxed">
                {country === 'US' 
                  ? "This service is void where prohibited by law. While we strive to adhere to all state-specific consumer protection regulations, users are responsible for verifying the applicability of specific tax rules. Consult a CPA or CFP®."
                  : "This tool is not regulated by the Financial Conduct Authority (FCA). Tax treatments (e.g., ISA, Pension relief) depend on individual circumstances and may change in the future. Consult a qualified Independent Financial Adviser (IFA)."
                }
              </p>
            </div>
         </div>
         
         <div className="border-t border-slate-200 pt-6 flex flex-col md:flex-row justify-between items-center gap-4">
            <p className="text-[10px] text-slate-300 font-medium">
              &copy; {currentYear} Retirement Planning Dashboard. All rights reserved.
            </p>
            <div className="flex gap-4">
               <span className="text-[10px] text-slate-300 cursor-pointer hover:text-slate-400">Privacy Policy</span>
               <span className="text-[10px] text-slate-300 cursor-pointer hover:text-slate-400">Terms of Service</span>
               <span className="text-[10px] text-slate-300 cursor-pointer hover:text-slate-400">Accessibility</span>
            </div>
         </div>
      </div>
    </footer>
  );
};
